apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: kibana-ingress
spec:
  rules:
    - host: a5edae9e6f27b429fa2b8e2bb9da99e2-956675905.us-east-1.elb.amazonaws.com
      http:
        paths:
          - path: /* 
            pathType: Prefix
            backend:
              service:
                name: kibana-kibana
                port:
                  number: 5601
