

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    app: node-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: 866308211434.dkr.ecr.us-east-1.amazonaws.com/node-js:1.2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      # imagePullSecrets:
      #   - name: myregistrysecret