# Shrink default JVM heap.
esJavaOpts: "-Xmx750m -Xms750m"

# environment:
#   ES_JAVA_OPTS: "-Xms750m -Xmx750m"

# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "1000m"
    memory: "4Gi"
  limits:
    cpu: "2000m"
    memory: "4Gi" 


# Request smaller persistent volumes.
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "gp2"
  resources:
    requests:
      storage: 10G

# This init container allows Elastic Search service access to volumes created for ES pods on EKS 
extraInitContainers:
  - name: init-volume-permission
    image: busybox
    command: ['chown', '-R', '1000:1000', '/usr/share/elasticsearch/']
    volumeMounts:
    - mountPath: /usr/share/elasticsearch/data
      name: elasticsearch-master
    securityContext:
      privileged: true
      runAsUser: 0
